version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/app/shared

  node1:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=1
    depends_on:
      - server

  node2:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=2
    depends_on:
      - server

  node3:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=3
    depends_on:
      - server

  node4:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=4
    depends_on:
      - server
