version: '3'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=1
      - NODE_PORT=5001
      - NODE_URLS=http://node2:5002,http://node3:5003,http://node4:5004
    volumes:
      - ./shared:/app/shared
    ports:
      - "5001:5001"
    networks:
      - distributed_net

  node2:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=2
      - NODE_PORT=5002
      - NODE_URLS=http://node1:5001,http://node3:5003,http://node4:5004
    volumes:
      - ./shared:/app/shared
    ports:
      - "5002:5002"
    networks:
      - distributed_net

  node3:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=3
      - NODE_PORT=5003
      - NODE_URLS=http://node1:5001,http://node2:5002,http://node4:5004
    volumes:
      - ./shared:/app/shared
    ports:
      - "5003:5003"
    networks:
      - distributed_net

  node4:
    build:
      context: .
      dockerfile: Dockerfile-node
    environment:
      - NODE_ID=4
      - NODE_PORT=5004
      - NODE_URLS=http://node1:5001,http://node2:5002,http://node3:5003
    volumes:
      - ./shared:/app/shared
    ports:
      - "5004:5004"
    networks:
      - distributed_net

networks:
  distributed_net:
    driver: bridge
